# Generated by Django 4.2 on 2023-05-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('bio', models.CharField(max_length=500)),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('goal_weight', models.IntegerField()),
                ('daily_calorie_goal', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
