# Generated by Django 4.2 on 2023-05-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0002_remove_userprofile_daily_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.TextField(blank=True),
        ),
    ]
