# Generated by Django 4.2 on 2023-05-08 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GetFit', '0006_rename_instagram_userprofile_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
