# Generated by Django 4.2 on 2023-06-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0020_group_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
    ]
