# Generated by Django 4.2 on 2023-06-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0024_remove_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invitation', 'Invitation-only')], default='public', max_length=20),
        ),
    ]
