# Generated by Django 4.2 on 2023-06-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0025_group_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
