# Generated by Django 4.2 on 2023-06-02 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GetFit', '0026_group_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_requests',
            field=models.ManyToManyField(related_name='group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
