# Generated by Django 4.2 on 2023-06-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0029_remove_group_join_requests_alter_joinrequest_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GetFit.group'),
        ),
    ]
