# Generated by Django 4.2 on 2023-06-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0032_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discussions/images'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='discussions/videos'),
        ),
    ]
