# Generated by Django 4.2 on 2023-06-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0034_group_invited_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='group',
            name='invited_users',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
