# Generated by Django 4.2 on 2023-06-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0037_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invitations',
            field=models.ManyToManyField(related_name='group_invitations', to='GetFit.invitation'),
        ),
    ]
