# Generated by Django 4.2 on 2023-06-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0038_group_invitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invitations',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
