# Generated by Django 4.2 on 2023-06-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0040_food_meal_dailyintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='foods',
        ),
        migrations.DeleteModel(
            name='DailyIntake',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
