# Generated by Django 4.2 on 2023-06-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0042_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
