# Generated by Django 4.2 on 2023-06-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0043_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fats', models.FloatField()),
            ],
        ),
    ]
