# Generated by Django 4.2 on 2023-06-25 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GetFit', '0045_foodlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodLog',
            new_name='FoodEntry',
        ),
    ]
