# Generated by Django 4.2 on 2023-06-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetFit', '0050_mealplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
